name: CI - Changed-Dirs
description: "Changed-Dirs"

inputs:
  IS_DEV:
    description: ""
    required: true
  IS_STG:
    description: ""
    required: true
  IS_PROD:
    description: ""
    required: true
  changed_functions:  
    description: 'Changed Lambda functions folders'
    required: true
  changed_step_functions:
    description: 'Changed step-function files'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "List of changed Lambda functions folders: ${{ inputs.changed_functions }}"
        echo "List of changed step-functions files: ${{ inputs.changed_step_functions }}"

        filtered_files=""

        if [ "${{ inputs.IS_DEV }}" == "true" ]; then
          echo "Filtering for dev environment"
          filtered_files=$(echo "${{ inputs.changed_step_functions }}" | tr ' ' '\n' | grep "^step-function-workflow/dev/" || true)
        elif [ "${{ inputs.IS_STG }}" == "true" ]; then
          echo "Filtering for stg environment"
          filtered_files=$(echo "${{ inputs.changed_step_functions }}" | tr ' ' '\n' | grep "^step-function-workflow/stg/" || true)
        elif [ "${{ inputs.IS_PROD }}" == "true" ]; then
          echo "Filtering for prod environment"
          filtered_files=$(echo "${{ inputs.changed_step_functions }}" | tr ' ' '\n' | grep "^step-function-workflow/prod/" || true)
        fi

        echo "Filtered step-function files for environment:"
        echo "$filtered_files"

        shell: bash

