name: CI - Changed-Dirs
description: "Changed-Dirs"

inputs:
  IS_DEV:
    description: "Is this a dev environment"
    required: true
  IS_STG:
    description: "Is this a staging environment"
    required: true
  IS_PROD:
    description: "Is this a production environment"
    required: true
  changed_functions:  
    description: 'Changed Lambda functions folders (JSON array or similar)'
    required: true
  changed_step_functions:
    description: 'Changed step-function files (JSON array or similar)'
    required: true

outputs:
  processed_folders:
    description: 'Processed unique Lambda function folders as JSON string'
    value: ${{ steps.main.outputs.processed_folders }}
  step_function_workflows:
    description: 'Filtered step-function files by environment as JSON string'
    value: ${{ steps.main.outputs.step_function_workflows }}

runs:
  using: "composite"
  steps:
    - id: main
      run: |
        
        # Check Step Function Code Changes
        step_function='${{ inputs.changed_step_functions }}'
        if [[ -z "$step_function" || "$step_function" == "[]" ]]; then
          step_function_workflows="[]"
        else
          echo "List of changed Step-functions files: ${{ inputs.changed_step_functions }}"
          formatted_changed_folders="[$(echo '${{ inputs.changed_step_functions }}' | sed -e 's/^\[//' -e 's/\]$//' | tr ', ' '\n' | sed '/^$/d; s/^"//; s/"$//; s/.*/"&"/' | paste -sd ',' -)]";
          echo "$formatted_changed_folders"
          if [ "${{ inputs.IS_DEV }}" = "true" ]; then
            step_function_workflows=$(echo "$formatted_changed_folders" | jq -r '[.[] | select(startswith("step-function-workflow/dev/"))]')
            echo "Step-function files for dev environment: $step_function_workflows"
          elif [ "${{ inputs.IS_STG }}" = "true" ]; then
            step_function_workflows=$(echo "$formatted_changed_folders" | jq -r '[.[] | select(startswith("step-function-workflow/stg/"))]')
            echo "Step-function files for stg environment: $step_function_workflows"
          elif [ "${{ inputs.IS_PROD }}" = "true" ]; then
            step_function_workflows=$(echo "$formatted_changed_folders" | jq -r '[.[] | select(startswith("step-function-workflow/prod/"))]')
            echo "Step-function files for prod environment: $step_function_workflows"
          else
            echo "No environment matched; no filtering applied"
          fi
        fi

        # Check Lambda Function Folder Changes
        changed_folders='${{ inputs.changed_functions }}'
        if [[ -z "$changed_folders" || "$changed_folders" == "[]" ]]; then
          processed_folders="[]"
        else
          echo "List of changed Lambda functions folders: ${{ inputs.changed_functions }}"
          formatted_changed_folders="[$(echo '${{ inputs.changed_functions }}' | sed -e 's/^\[//' -e 's/\]$//' | tr ', ' '\n' | sed '/^$/d; s/^"//; s/"$//; s/.*/"&"/' | paste -sd , -)]"
          processed_folders=$(echo "$formatted_changed_folders" | jq -r 'map(split("/")[0:2] | join("/")) | unique')
          if [[ "$processed_folders" == "null" ]]; then
              processed_folders="[]"
          else
              echo "Lambda function folders: $processed_folders" 
          fi
        fi

        echo "step_function_workflows=$(echo $step_function_workflows | jq -c .)" >> "$GITHUB_OUTPUT"
        echo "processed_folders=$(echo $processed_folders | jq -c .)" >> "$GITHUB_OUTPUT"

      shell: bash





















