name: Changed Directories Extractor
description: Extract and print changed directories and files

inputs:
  changed_functions:
    required: true
  changed_step_functions:
    required: true
  IS_DEV:
    required: false
  IS_STG:
    required: false
  IS_PROD:
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        echo "Changed Lambda functions folders: ${{ inputs.changed_functions }}"
        echo "Changed step-functions files: ${{ inputs.changed_step_functions }}"
      shell: bash
