name: Jaime-DataCollection

on:
  workflow_dispatch: {}

  push:
    branches:
      - "release/*"
      - "develop/*"
    tags:
      - "v*.*.*"
    paths:
      - functions/**
      - step-function-workflow/**

permissions:
  id-token: write
  contents: read

jobs:
  changed_files:
    environment: "build"
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.extract-folders.outputs.processed_folders }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed directories for functions
        id: changed-function-directories
        # if: github.ref_type == 'branch' && github.ref_name == 'main' || github.ref_type == 'tag' || github.event_name == 'pull_request'
        if: github.ref_type == 'branch' && startsWith(github.ref_name, 'develop') || startsWith(github.ref_name, 'hotfixes') || startsWith(github.ref_name, 'release') || github.ref_type == 'tag' || github.event_name == 'pull_request'
        uses: tj-actions/changed-files@v46.0.1
        with:
          dir_names: true
          diff_relative: true
          dir_names_max_depth: "5"
          matrix: "true"
          files: |
            functions/**
      
      - name: Get changed files for step-function-workflow
        id: changed-Step-function-files
        # if: github.ref_type == 'branch' && github.ref_name == 'main' || github.ref_type == 'tag' || github.event_name == 'pull_request'
        if: github.ref_type == 'branch' && startsWith(github.ref_name, 'develop') || startsWith(github.ref_name, 'hotfixes') || startsWith(github.ref_name, 'release') || github.ref_type == 'tag' || github.event_name == 'pull_request'
        uses: tj-actions/changed-files@v46.0.1
        with:
          diff_relative: true
          dir_names_max_depth: "5"
          matrix: "true"
          files: |
            step-function-workflow/**

      - name: Extract top-level folders
        id: extract-folders
        run: |
          changed_folders="${{ steps.changed-function-directories.outputs.all_changed_files }}"
          echo "List of changed functions folders: $changed_folders"

          changed_files="${{ steps.changed-Step-function-files.outputs.all_changed_files }}"
          echo "List of changed step-functions files: $changed_folders"

